services:
  - type: web
    name: spacy-flask-app
    env: python
    region: oregon
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: OPENAI_API_KEY
        sync: true  # This ensures the key is pulled from Render's environment variables
