services:
  - type: web
    name: your-service-name
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m spacy download en_core_web_sm
      python -m spacy link en_core_web_sm en
    startCommand: gunicorn app:app
    envVars:
      - key: PIP_NO_CACHE_DIR
        value: "false"
      - key: INSTALL_PACKAGES
        value: "gcc python3-dev musl-dev"