services:
  - type: web
    name: my-flask-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:5000 app:app
    envVars:
      - key: FLASK_ENV
        value: production
    docker:
      systemPackages:
        - gcc
        - python3-dev
        - musl-dev
